DELETE FROM PESSOA
GO

INSERT INTO PESSOA(NOME) VALUES('Lauan Borges Guermandi');
GO

DECLARE @IDPESSOA UNIQUEIDENTIFIER = (
    SELECT IDPESSOA FROM PESSOA WHERE NOME = 'Lauan Borges Guermandi');

INSERT INTO PESSOACONTATO(EMAIL, TELEFONE, IDPESSOA) VALUES('lauanguermandi@gmail.com', '14998671107', @IDPESSOA);
