ALTER DATABASE PROJETOAPLICADO SET OFFLINE WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE PROJETOAPLICADO SET ONLINE;
GO

DROP DATABASE IF EXISTS PROJETOAPLICADO
GO

CREATE DATABASE PROJETOAPLICADO
GO

USE PROJETOAPLICADO
GO

CREATE TABLE PESSOA
(
	IDPESSOA UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	NOME VARCHAR(255) NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1
)
GO

CREATE TABLE PESSOAFISICA
(
	IDPESSOAFISICA UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	CPF VARCHAR(11) NOT NULL,
    IDPESSOA UNIQUEIDENTIFIER NOT NULL,
)
GO

CREATE TABLE PESSOAJURIDICA
(
	IDPESSOAJURIDICA UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	CNPJ VARCHAR(14) NOT NULL,
    IDPESSOA UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE PESSOATELEFONE
(
	IDPESSOATELEFONE UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	CODIGO INT NOT NULL,
	NUMERO INT NOT NULL,
    IDPESSOA UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE PESSOAEMAIL
(
	IDPESSOAEMAIL UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	EMAIL VARCHAR(255) NOT NULL,
    IDPESSOA UNIQUEIDENTIFIER NOT NULL
)
GO

ALTER TABLE PESSOAFISICA ADD CONSTRAINT FK_PESSOAFISICA_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA);
GO
ALTER TABLE PESSOAJURIDICA ADD CONSTRAINT FK_PESSOAJURIDICA_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA);
GO
ALTER TABLE PESSOATELEFONE ADD CONSTRAINT FK_PESSOATELEFONE_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA);
GO
ALTER TABLE PESSOAEMAIL ADD CONSTRAINT FK_PESSOAEMAIL_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA);
GO
