ALTER DATABASE PROJETOAPLICADO SET OFFLINE WITH ROLLBACK IMMEDIATE;
GO
ALTER DATABASE PROJETOAPLICADO SET ONLINE;
GO

DROP DATABASE IF EXISTS PROJETOAPLICADO
GO

CREATE DATABASE PROJETOAPLICADO
GO

USE PROJETOAPLICADO
GO

CREATE TABLE PESSOA
(
	IDPESSOA BIGINT PRIMARY KEY IDENTITY,
	NOME VARCHAR(255) NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1
)
GO

CREATE TABLE PESSOACONTATO
(
	IDPESSOACONTATO BIGINT PRIMARY KEY IDENTITY,
	EMAIL VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(20) NOT NULL,
    IDPESSOA BIGINT NOT NULL,
	ATIVO BIT NOT NULL DEFAULT 1
)
GO

ALTER TABLE PESSOACONTATO ADD CONSTRAINT FK_PESSOACONTATO_PESSOA FOREIGN KEY (IDPESSOA) REFERENCES PESSOA(IDPESSOA);
GO